version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
  build:
    commands:
      - . ./assume-role.sh ${ENV_PIPELINE_EXECUTION_ROLE} deploy
      - sam deploy --stack-name ${ENV_STACK_NAME}
                    --template ${ENV_TEMPLATE}
                    --capabilities CAPABILITY_IAM
                    --region ${ENV_REGION}
                    {%- if cookiecutter.testing_artifacts_bucket %}
                    --s3-bucket ${ENV_BUCKET}
                    {%- endif %}
                    {%- if cookiecutter.testing_artifacts_bucket_prefix_sam %}
                    --s3-prefix ${ENV_BUCKET_PREFIX}
                    {%- endif %}
                    {%- if cookiecutter.testing_image_repository %}
                    --image-repository ${ENV_IMAGE_REPOSITORY}
                    {%- endif %}
                    --no-fail-on-empty-changeset
                    --role-arn ${ENV_CLOUDFORMATION_EXECUTION_ROLE}
